// <auto-generated />
namespace ClubApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LittleC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LittleC));
        
        string IMigrationMetadata.Id
        {
            get { return "202001150650046_LittleC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
